name: Continuous Integration 

on:

  push:

    branches:

      - main

  workflow_dispatch:


jobs:

  CICD_homework_runner:

    runs-on: ubuntu-latest

    steps:

   

    - name: Set up JDK 17

      uses: actions/setup-java@v4

      with:

        java-version: '17'

        distribution: 'zulu'

    - name: Show Java version

      run: "java -version"

    - name: Checkout code

      uses: actions/checkout@v4

    - name: Show directory

      run: 'pwd'

    - name: List files

      run: 'ls -al'

    - name: Install Dependencies

      run: 'mvn compile'

    - name: Set permissions

      run: chmod 755 ./mvnw

    - name: Build application

      run: './mvnw clean package -DskipTests'

    - name: Test application

      run: 'mvn test'
